"""
Django settings for vafadari project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('PROJECT_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jalali_date',  

    'account',
    'moshtari',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vafadari.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'moshtari.context_processor.add_variable_to_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'vafadari.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'postgres', 
#         'USER': 'postgres',
#         'PASSWORD': 'My:s3Cr3t/',
#         'HOST': '0.0.0.0',
#         'PORT': '5455',
#     }
# }
DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': os.getenv('DB_NAME'),
         'USER': os.getenv('DB_USER_NAME'),
         'PASSWORD': os.getenv('DB_PASSWORD'),
         'HOST': 'localhost',
         'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
             'charset': 'utf8mb4',
         },
     }
 }
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# import locale
# locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")
LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_VERSION = '1.0'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGIN_REDIRECT_URL ='/search'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


AUTH_USER_MODEL = 'account.User'
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_AUTHENTICATION_METHOD = 'id_card_num'
# LOGIN_URL = '127.verify/' 
handler404 = 'account.views.custom_404'


PHONENUMBER_DEFAULT_REGION = "IR"



STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   

STATICFILES_DIRS = [BASE_DIR / 'static']
# SECURE_SSL_REDIRECT = True

JALALI_DATE_DEFAULTS = {
   'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}
DATA_KEY_LIST = ['send', 'use', 'is']


# Define media root directory 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Define the URL for media files
MEDIA_URL = '/media/'


PERSONAL_SECRET_KEY = os.getenv('PERSONAL_SECRET_KEY')
COMAPANY_SECRET_KEY = os.getenv('COMAPANY_SECRET_KEY')
ACCOUNTANT_URL = os.getenv('ACCOUNTANT_URL')

ACCOUNTANT_BODY = {
  "fromOrderDetailVersion": 0,
  "fromOrderVersion": 0,
  "fromPersonVersion": 0,
    "fromProductDetailVersion": 0,
  "fromProductVersion": 0
 
}


PERSONAL_ACCOUNTANT_LOGIN = {
  "userName": "2515293",
  "password": "196744",
  "databaseId": 2795476, 
  "packageNo": "2515293",
  "language": "fa",
  "appId": "string",
  "description": "string",
  "token": "string"
}
COMPANY_ACCOUNTANT_LOGIN = {
  "userName": "2515293",
  "password": "196744",
  "databaseId": 2795251, 
  "packageNo": "2515293",
  "language": "fa",
  "appId": "string",
  "description": "string",
  "token": "string"
}


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

ACCOUNTANT_TOKEN_URL = "https://mahakacc.mahaksoft.com/API/v3/Sync/Login"

CELERY_BEAT_SCHEDULE = {
    "send_otp_to_phone_number": {
        'task': "account.tasks.send_birthday_msg_and_stamp_card",
        'schedule': crontab(hour="8", minute="0"),
        # 'schedule': 60,
        'args': [3],
        # 'kwargs': {}
    }
}

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_VERSION = '1.0'

