# Generated by Django 3.2 on 2024-12-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date_status',
            field=models.BooleanField(default=False, verbose_name='تایید تاریخ تولد '),
        ),
    ]
