# Generated by Django 3.2 on 2024-08-27 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد جشنواره')),
                ('name', models.CharField(default='جشنواره', max_length=300, verbose_name='نام جشنواره')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('min_stamp', models.IntegerField(verbose_name='حداقل تعداد مهر')),
                ('number_of_winners', models.PositiveBigIntegerField(verbose_name='تعداد برندگان جشنواره')),
                ('winners_prizes', models.JSONField(default=dict, verbose_name='جایزه بدندگان')),
                ('lottery_was_done', models.BooleanField(default=False, verbose_name=' قرعه کشی انجام شده')),
                ('first_winner_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره شانس اولین برنده')),
                ('all_taken_stamps', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='کل مهرهای اخذ شده در جشنواره')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد گام')),
                ('number_one_stamps', models.IntegerField(default=0, verbose_name='مهرهای نفر اول جشنواره')),
                ('description_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='لینک توضیحات')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='excel_files/', verbose_name='فایل اکسل')),
                ('winner_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک لیست برندگان')),
            ],
            options={
                'verbose_name': 'جشنواره',
                'verbose_name_plural': 'جشنواره ها',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailRowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_version_person', models.IntegerField(default=0, help_text='برای گرفتن OrderDetail از این ورژن', verbose_name=' راو ورژن شخصی')),
                ('row_version_company', models.IntegerField(default=0, help_text='برای گرفتن OrderDetail از این ورژن', verbose_name='راو ورژن شرکت')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال پیامک')),
                ('receviver_full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی گیرنده')),
                ('recevier_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='شماره موبایل گیرنده')),
                ('message', models.CharField(max_length=1000, verbose_name='متن پیام')),
                ('is_successfull', models.BooleanField(default=False, verbose_name='ارسال موفق')),
                ('response_message', models.CharField(max_length=500, verbose_name='ریسپانس پیامک ارسالی')),
                ('status_code', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'پیامک ارسالی',
                'verbose_name_plural': 'پیامک های ارسالی',
            },
        ),
        migrations.CreateModel(
            name='stamp_reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='دلیل مهر')),
                ('used_count', models.IntegerField(blank=True, default=0, verbose_name='تعداد استفاده شده')),
            ],
            options={
                'verbose_name': 'دلیل مهر',
                'verbose_name_plural': 'دلیل های مهر زدن',
            },
        ),
        migrations.CreateModel(
            name='UserTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_tick_table', models.JSONField(default=dict, verbose_name='جدول مشتری')),
                ('big_award', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='جایزه بزرگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد جدول')),
            ],
            options={
                'verbose_name': 'کارت  تنظیم شده سایت',
                'verbose_name_plural': 'کارت های تنظیم شده سایت',
            },
        ),
        migrations.CreateModel(
            name='UserGiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_tick_table', models.JSONField(default=dict, verbose_name='جدول مشتری')),
                ('big_award', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='جایزه بزرگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد جدول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارت مخصوص کاربر',
                'verbose_name_plural': 'کارت های مخصوص کاربر',
            },
        ),
        migrations.CreateModel(
            name='FestivalMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_chance_number_list', models.TextField(blank=True, null=True, verbose_name='شماره های شانس در جشنواره')),
                ('win', models.BooleanField(default=False, verbose_name='برنده هست؟')),
                ('taken_stamps', models.PositiveBigIntegerField(default=0, verbose_name='تعداد مهر گرفته شده در این جشنواره')),
                ('rank', models.PositiveBigIntegerField(default=0, verbose_name='رتبه در جشنواره')),
                ('message_status', models.CharField(blank=True, max_length=3, null=True, verbose_name='وضعیت ارسال پیامک')),
                ('message_content', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن پیام')),
                ('prize', models.CharField(blank=True, max_length=500, null=True, verbose_name='جایزه')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moshtari.festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' مادل میانجی جشنواره یوزر',
                'verbose_name_plural': 'مادل های میانجی حشنواره یورز',
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='members',
            field=models.ManyToManyField(through='moshtari.FestivalMembers', to=settings.AUTH_USER_MODEL, verbose_name='لیست شرکت کنندگان'),
        ),
    ]
