# Generated by Django 3.2 on 2024-09-05 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshtari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp_reasons',
            name='limit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر تعداد مهر'),
        ),
    ]
