# Generated by Django 3.2 on 2024-09-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshtari', '0003_alter_stamp_reasons_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailrowversion',
            name='row_version_company',
            field=models.BigIntegerField(default=0, help_text='برای گرفتن OrderDetail از این ورژن', verbose_name='راو ورژن شرکت'),
        ),
        migrations.AlterField(
            model_name='orderdetailrowversion',
            name='row_version_person',
            field=models.BigIntegerField(default=0, help_text='برای گرفتن OrderDetail از این ورژن', verbose_name=' راو ورژن شخصی'),
        ),
    ]
